# Generated by Django 3.1.3 on 2021-06-04 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_face_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='global_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
