# Generated by Django 3.1.3 on 2021-05-31 06:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210531_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 31, 6, 26, 36, 945738), editable=False, null=True),
        ),
    ]
