# Generated by Django 3.1.3 on 2021-05-31 06:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210531_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True),
        ),
    ]
